In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.mean([1,2,3,4,5])

3.0

In [4]:
t=(1,2,3,4,5)

In [5]:
np.mean(t)

3.0

In [6]:
np.min([1,2,3,4,5])

1

In [7]:
np.max([1,2,3,4,5])

5

In [8]:
def sum_fun(*args):
    total=0
    for i in args:
        total+=i

    return total

sum_fun(1,2,3,4,5)

15

In [9]:
np.random.randint(10,20,10)

array([16, 11, 14, 10, 10, 19, 19, 14, 15, 11])

In [10]:
np.random.randint(10,20,[5])

array([14, 18, 11, 17, 16])

In [11]:
l=[1,2,3,4,5]

In [12]:
type(l)

list

1D travel in one direction 
2D travel in two direction
3D travel in three direction

In [13]:
l=np.array(l)

In [14]:
type(l)

numpy.ndarray

In [15]:
l

array([1, 2, 3, 4, 5])

In [16]:
l.ndim

1

In [17]:
a=[[1,2,3],[4,5,6]]

In [18]:
type(a)

list

In [19]:
a=np.array(a)

In [20]:
type(a)

numpy.ndarray

In [21]:
a.ndim

2

In [22]:
t=[[[1,2,3],[4,5,6],[7,8,9]]]

In [23]:
type(t)

list

In [24]:
t=np.array(t)

In [25]:
t.ndim

3

In [26]:
np.random.rand(2,3)

array([[0.90219983, 0.58927829, 0.38931675],
       [0.10219928, 0.67422304, 0.86363417]])

In [27]:
np.random.rand(2,3,2)

array([[[0.2205451 , 0.75225116],
        [0.8919297 , 0.955346  ],
        [0.9927122 , 0.43078443]],

       [[0.12191744, 0.68190412],
        [0.88437089, 0.13549327],
        [0.37534742, 0.7108098 ]]])

In [28]:
np.random.rand(2,3,2,2)

array([[[[0.31067829, 0.73091033],
         [0.89585391, 0.39753633]],

        [[0.99858251, 0.83605868],
         [0.52634068, 0.59791986]],

        [[0.76090635, 0.76220902],
         [0.05199949, 0.98075437]]],


       [[[0.65041119, 0.84615941],
         [0.74542828, 0.35378431]],

        [[0.26468216, 0.21472663],
         [0.24046763, 0.25783358]],

        [[0.09041997, 0.78622227],
         [0.42048027, 0.66035762]]]])

In [29]:
np.random.randint(0,10,(4,4))

array([[9, 0, 1, 1],
       [7, 6, 0, 3],
       [6, 8, 6, 9],
       [7, 7, 9, 0]])